name: Build Binaries

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Build with xgo
        uses: crazy-max/ghaction-xgo@v3
        with:
          go_version: latest
          targets: windows/amd64,linux/amd64,linux/arm64,darwin/arm64
          dest: release # Output directory for binaries
          prefix: blipgloss
          ldflags: -s -w
          buildmode: c-shared

      - name: Upload Binaries Artifact
        uses: actions/upload-artifact@v4
        with:
          name: blipgloss-binaries
          path: release/ 
