name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    permissions:
      contents: write # to create release (changesets/action)
      pull-requests: write # to create pull request (changesets/action)
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - run: bun install

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: bun run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Get Latest Release
        if: ${{ steps.changesets.outputs.published == 'true' }}
        id: get-release
        run: |
          TAG=$(curl -s "https://api.github.com/repos/${{ github.repository }}/releases/latest" | jq -r '.tag_name')
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Build Binaries
        if: ${{ steps.changesets.outputs.published == 'true' }}
        uses: crazy-max/ghaction-xgo@v3
        with:
          go_version: latest
          targets: windows/amd64,linux/amd64,linux/arm64,darwin/arm64
          dest: bin # Output directory for binaries
          prefix: blipgloss
          ldflags: -s -w
          buildmode: c-shared

      - name: Upload Binaries to Release
        if: ${{ steps.changesets.outputs.published == 'true' }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get-release.outputs.tag }}
          files: |
            bin/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
