name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    permissions:
      contents: write # to create release (changesets/action)
      pull-requests: write # to create pull request (changesets/action)
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Download Binaries Artifact
        uses: actions/download-artifact@v4
        with:
          name: blipgloss-binaries
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check Binaries Freshness
        run: |
          ARTIFACT_COMMIT=$(cat release/.binaries-commit)
          CURRENT_COMMIT=${{ github.sha }}
          if [ "$ARTIFACT_COMMIT" != "$CURRENT_COMMIT" ]; then
            echo "Error: Binaries artifact built from commit $ARTIFACT_COMMIT does not match current commit $CURRENT_COMMIT."
            echo "Please manually trigger the 'Build Binaries' workflow for the latest commit." >&2
            exit 1
          else
            echo "Binaries artifact commit $ARTIFACT_COMMIT matches current commit. Proceeding with release."
          fi

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - run: bun install

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: bun run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
