name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    permissions:
      contents: write # to create release (changesets/action)
      pull-requests: write # to create pull request (changesets/action)
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Get Latest Build Run ID
        id: get-run
        run: |
          LATEST_RUN=$(curl -s -H "Authorization: token ${{ secrets.GH_PAT }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/workflows/build-binaries.yml/runs?branch=${{ github.ref_name }}&status=success&per_page=1" \
            | jq -r '.workflow_runs[0].id')
          echo "run_id=$LATEST_RUN" >> $GITHUB_OUTPUT

      - name: Download Binaries Artifact
        uses: actions/download-artifact@v4
        with:
          name: blipgloss-binaries
          path: ./release
          run-id: ${{ steps.get-run.outputs.run_id }}
          github-token: ${{ secrets.GH_PAT }}
          repository: ${{ github.repository }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - run: bun install

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: bun run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
